(in-package :mu-cl-resources)

(define-resource book ()
  :class (s-prefix "schema:Book")
  :properties `((:series :string ,(s-prefix "schema:ComicSeries"))
                (:author :string ,(s-prefix "schema:author"))
                (:title :string ,(s-prefix "schema:title"))
                (:number :string ,(s-prefix "schema:SerialNumber")))
  :has-one `((user :via ,(s-prefix "schema:owner")
                    :as "owner"))
  :resource-base (s-url "http://mu.semte.ch/services/books/")
  :on-path "books")

(define-resource user ()
    :class (s-prefix "foaf:Person")
    :properties `((:name :string ,(s-prefix "foaf:name")))
    :has-many `((account :via ,(s-prefix "foaf:account")
                        :as "accounts")
                 (book :via ,(s-prefix "schema:owner")
                       :inverse t
                       :as "books"))
    :resource-base (s-url "http://mu.semte.ch/services/registration-service/users/")
    :on-path "users")

(define-resource account ()
    :class (s-prefix "foaf:OnlineAccount")
    :properties `((:name :string ,(s-prefix "foaf:accountName")))
    :has-one `((user :via ,(s-prefix "foaf:account")
                     :inverse t
                     :as "owner"))
    :resource-base (s-url "http://mu.semte.ch/services/registration-service/accounts/")
    :on-path "user-accounts")

(define-resource file ()
  :class (s-prefix "nfo:FileDataObject")
  :properties `((:name :string ,(s-prefix "nfo:fileName"))
                (:format :string ,(s-prefix "dct:format"))
                (:size :number ,(s-prefix "nfo:fileSize"))
                (:extension :string ,(s-prefix "dbpedia:fileExtension"))
                (:created :datetime ,(s-prefix "nfo:fileCreated")))
  :has-one `((file :via ,(s-prefix "nie:dataSource")
                   :inverse t
                   :as "download"))
  :resource-base (s-url "http://data.example.com/files/")
  :features `(include-uri)
  :on-path "files")